services:
  db:
    volumes:
      - prod_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    environment:
      MODE: "prod"
      RUN_MIGRATIONS: True
    ports:
      - "8000:8000"
volumes:
  prod_db_data: