services:
  db:
    environment:
      POSTGRES_DB: test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql+asyncpg://wallet_user:1234@db:5432/test_db"
      MODE: "test"
    ports:
      - "8000:8000"


  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: "postgresql+asyncpg://wallet_user:1234@db:5432/test_db"
      TEST_DATABASE_URL: "postgresql://wallet_user:1234@db:5432/test_db"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
    volumes:
      - ./:/app
    command: ["bash", "-lc", "pytest -q tests --maxfail=1"]
